# Service for AuthorizationManager
apiVersion: v1
kind: Service
metadata:
  name: authmanager
  namespace: muzika
  labels:
    app: authmanager
    app.kubernetes.io/name: authmanager
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: muzika-platform
spec:
  type: LoadBalancer
  loadBalancerSourceRanges:
    - 20.24.122.172/32
  ports:
    - name: http
      port: 8091
      targetPort: 8091
      protocol: TCP
  selector:
    app: authmanager
